import { FormEvent, useEffect, useMemo, useState } from 'react'
import type { AuthSession } from './auth'
import { ContextualPageHeading } from './ContextualPageHeading'

const catalogApiUrl = import.meta.env.VITE_CATALOG_API_URL ?? 'http://localhost:8085/api'
const customerApiUrl = import.meta.env.VITE_CUSTOMER_API_URL ?? 'http://localhost:8082/api'
const loadError = 'Não foi possível carregar a informação.'
const saveError = 'Não foi possível guardar. Confirme os dados indicados.'

type Group = { id:string; designation:string; active:boolean; updatedAt:string; updatedBy:string }
type Zone = { id:string; code:string; designation:string; zoneType:'DESTINATION_POSTAL_CODES'; country:string; groupName:string|null; active:boolean; postalCodePatterns:string[]; updatedAt:string; updatedBy:string }
type CustomerRef = { id:string; customerCode:string; shippingName:string }
type Summary = { id:string; code:string; designation:string; groupId:string; groupDesignation:string; transportType:'LARGE_VOLUMES'|'SMALL_VOLUMES'; active:boolean; urgency:number; zoneCount:number; updatedAt:string; updatedBy:string }
type PackageType = 'BOX'|'DOCUMENT'|'PALLET'
type Day = 'MONDAY'|'TUESDAY'|'WEDNESDAY'|'THURSDAY'|'FRIDAY'|'SATURDAY'|'SUNDAY'
type PackageLimit = { packageType:PackageType; maxWeightKg:number|null; maxLengthCm:number|null; maxWidthCm:number|null; maxHeightCm:number|null; maxCombinedCm:number|null }
type ZoneRule = { billingZoneId:string; transitMinHours:number|null; transitMaxHours:number|null }
type ServiceRequest = {
  identity:{code:string;designation:string;groupId:string;transportType:'LARGE_VOLUMES'|'SMALL_VOLUMES';active:boolean}
  transit:{transitMinHours:number|null;transitMaxHours:number|null;deliveryCutoff:string|null;urgency:number;zones:ZoneRule[]}
  pricing:{priceCalculationRule:'WEIGHT';salesCalculationRule:'DEFAULT';forcedCarrier:string|null;vatMode:'AUTO'|'STANDARD'|'ZERO'|'EXEMPT';pricePerVolume:boolean;pricePerCubicMeter:boolean;pricePerDimensions:boolean;priceByBracket:boolean}
  limits:{packageLimits:PackageLimit[];totalVolumesMin:number|null;totalVolumesMax:number|null;totalWeightMinKg:number|null;totalWeightMaxKg:number|null}
  schedule:{pickupStart:string|null;pickupEnd:string|null;minimumAdvanceMinutes:number|null;pickupDays:Day[];deliveryDays:Day[]}
  pickupRules:{associatedPickupServiceId:string|null;intercityPickupServiceId:string|null}
  characteristics:{pickupOnly:boolean;mailVatZero:boolean;international:boolean;seaTransport:boolean;airTransport:boolean;courier:boolean;forceImport:boolean;forceExport:boolean}
  additionalServices:{allowsCod:boolean;allowsReturn:boolean;allowsPudo:boolean;requiresDeliveryPin:boolean}
  definitions:{requiresEmail:boolean;autoSubmitWebservice:boolean;requiresKilometres:boolean;forceReturn:boolean;noPickup:boolean;requiresDimensions:boolean;insuredValue:boolean;mapIdentifier:string|null}
  restrictions:{exclusiveCustomerIds:string[];blockedAgencies:string[]}
}
type ServiceDetail = ServiceRequest & { id:string; createdAt:string;createdBy:string;updatedAt:string;updatedBy:string;version:number }

const days: {id:Day;label:string}[] = [
  {id:'MONDAY',label:'Seg'}, {id:'TUESDAY',label:'Ter'}, {id:'WEDNESDAY',label:'Qua'},
  {id:'THURSDAY',label:'Qui'}, {id:'FRIDAY',label:'Sex'}, {id:'SATURDAY',label:'Sáb'}, {id:'SUNDAY',label:'Dom'},
]
const packages: {id:PackageType;label:string}[] = [{id:'BOX',label:'Caixa'},{id:'DOCUMENT',label:'Documento'},{id:'PALLET',label:'Palete'}]

function emptyService(): ServiceRequest { return {
  identity:{code:'',designation:'',groupId:'',transportType:'SMALL_VOLUMES',active:true},
  transit:{transitMinHours:null,transitMaxHours:null,deliveryCutoff:null,urgency:3,zones:[]},
  pricing:{priceCalculationRule:'WEIGHT',salesCalculationRule:'DEFAULT',forcedCarrier:null,vatMode:'AUTO',pricePerVolume:false,pricePerCubicMeter:false,pricePerDimensions:false,priceByBracket:false},
  limits:{packageLimits:[],totalVolumesMin:null,totalVolumesMax:null,totalWeightMinKg:null,totalWeightMaxKg:null},
  schedule:{pickupStart:null,pickupEnd:null,minimumAdvanceMinutes:null,pickupDays:['MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY'],deliveryDays:['MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY']},
  pickupRules:{associatedPickupServiceId:null,intercityPickupServiceId:null},
  characteristics:{pickupOnly:false,mailVatZero:false,international:false,seaTransport:false,airTransport:false,courier:false,forceImport:false,forceExport:false},
  additionalServices:{allowsCod:false,allowsReturn:false,allowsPudo:false,requiresDeliveryPin:false},
  definitions:{requiresEmail:false,autoSubmitWebservice:false,requiresKilometres:false,forceReturn:false,noPickup:false,requiresDimensions:false,insuredValue:false,mapIdentifier:null},
  restrictions:{exclusiveCustomerIds:[],blockedAgencies:[]},
} }

async function json<T>(auth:AuthSession, url:string, options?:RequestInit):Promise<T> {
  const response = await auth.fetch(url, options)
  if (!response.ok) throw new Error(String(response.status))
  return response.json() as Promise<T>
}
function navigate(path:string){ window.history.pushState({},'',path); window.dispatchEvent(new PopStateEvent('popstate')) }
function numberOrNull(value:string){ return value === '' ? null : Number(value) }

export function OperationalServicesPage({auth}:{auth:AuthSession}) {
  const [items,setItems]=useState<Summary[]>([]), [loading,setLoading]=useState(true), [error,setError]=useState(''), [query,setQuery]=useState(''), [status,setStatus]=useState('ALL')
  const canManage=auth.roles.includes('ADMIN')
  async function load(){ setLoading(true); try{setItems(await json<Summary[]>(auth,`${catalogApiUrl}/operational-services`));setError('')}catch{setError(loadError)}finally{setLoading(false)} }
  useEffect(()=>{void load()},[])
  const filtered=useMemo(()=>items.filter(item=>(status==='ALL'||item.active===(status==='ACTIVE'))&&`${item.code} ${item.designation} ${item.groupDesignation}`.toLowerCase().includes(query.toLowerCase())),[items,query,status])
  async function toggle(item:Summary){ if(!confirm(`${item.active?'Inativar':'Ativar'} o serviço ${item.designation}?`))return; try{await json(auth,`${catalogApiUrl}/operational-services/${item.id}/status`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({active:!item.active})});await load()}catch{setError(saveError)} }
  return <main className="workspace-page operational-page"><ContextualPageHeading title="Serviços" trail={['Configuração comercial','Serviços operacionais']}/>
    <section className="panel catalog-panel"><div className="catalog-toolbar"><div>{canManage&&<button onClick={()=>navigate('/configuracao/servicos/create')}>+ Novo serviço</button>}<label>Pesquisar<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Código, designação ou grupo"/></label><label>Estado<select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">Todos</option><option value="ACTIVE">Ativos</option><option value="INACTIVE">Inativos</option></select></label></div><span>{filtered.length} serviços</span></div>
      {error&&<p className="error">{error}</p>}{loading?<p>A carregar…</p>:<div className="table-wrap"><table><thead><tr><th>Código</th><th>Designação</th><th>Grupo</th><th>Transporte</th><th>Urgência</th><th>Zonas</th><th>Estado</th><th>Ações</th></tr></thead><tbody>{filtered.map(item=><tr key={item.id}><td><strong>{item.code}</strong></td><td>{item.designation}<small>Alterado por {item.updatedBy}</small></td><td>{item.groupDesignation}</td><td>{item.transportType==='LARGE_VOLUMES'?'Grandes volumes':'Pequenos volumes'}</td><td>{item.urgency}/5</td><td>{item.zoneCount}</td><td><span className={`badge ${item.active?'active':''}`}>{item.active?'Ativo':'Inativo'}</span></td><td><div className="row-actions"><button className="secondary" onClick={()=>navigate(`/configuracao/servicos/${item.id}/edit`)}>Consultar{canManage?' / editar':''}</button>{canManage&&<button className="danger-link" onClick={()=>void toggle(item)}>{item.active?'Inativar':'Ativar'}</button>}</div></td></tr>)}</tbody></table></div>}
    </section></main>
}

export function OperationalServiceEditorPage({auth,id}:{auth:AuthSession;id?:string}) {
  const canManage=auth.roles.includes('ADMIN'), editing=Boolean(id)
  const [form,setForm]=useState<ServiceRequest>(emptyService()), [groups,setGroups]=useState<Group[]>([]), [zones,setZones]=useState<Zone[]>([]), [services,setServices]=useState<Summary[]>([]), [customers,setCustomers]=useState<CustomerRef[]>([])
  const [error,setError]=useState(''), [saving,setSaving]=useState(false), [zoneQuery,setZoneQuery]=useState(''), [customerQuery,setCustomerQuery]=useState('')
  function mergeCustomers(values:CustomerRef[]){setCustomers(current=>Array.from(new Map([...current,...values].map(value=>[value.id,value])).values()))}
  useEffect(()=>{void(async()=>{try{const [g,z,s,c]=await Promise.all([json<Group[]>(auth,`${catalogApiUrl}/service-groups?active=true`),json<Zone[]>(auth,`${catalogApiUrl}/billing/zones?active=true`),json<Summary[]>(auth,`${catalogApiUrl}/operational-services?active=true`),json<{content:CustomerRef[]}>(auth,`${customerApiUrl}/customers?page=0&size=50&active=true`)]);setGroups(g);setZones(z);setServices(s);mergeCustomers(c.content);if(id){const value=await json<ServiceDetail>(auth,`${catalogApiUrl}/operational-services/${id}`);setForm(value);const selected=await Promise.all(value.restrictions.exclusiveCustomerIds.map(customerId=>json<CustomerRef>(auth,`${customerApiUrl}/customers/${customerId}`)));mergeCustomers(selected)}}catch{setError(loadError)}})()},[id])
  useEffect(()=>{const timer=window.setTimeout(()=>{void(async()=>{try{const result=await json<{content:CustomerRef[]}>(auth,`${customerApiUrl}/customers?page=0&size=50&active=true&query=${encodeURIComponent(customerQuery.trim())}`);mergeCustomers(result.content)}catch{setError(loadError)}})()},250);return()=>window.clearTimeout(timer)},[customerQuery])
  function block<K extends keyof ServiceRequest>(name:K,value:ServiceRequest[K]){setForm(current=>({...current,[name]:value}))}
  function toggleZone(zone:Zone){const exists=form.transit.zones.some(value=>value.billingZoneId===zone.id);block('transit',{...form.transit,zones:exists?form.transit.zones.filter(value=>value.billingZoneId!==zone.id):[...form.transit.zones,{billingZoneId:zone.id,transitMinHours:null,transitMaxHours:null}]})}
  function packageLimit(type:PackageType){return form.limits.packageLimits.find(value=>value.packageType===type)}
  function togglePackage(type:PackageType){const exists=packageLimit(type);block('limits',{...form.limits,packageLimits:exists?form.limits.packageLimits.filter(value=>value.packageType!==type):[...form.limits.packageLimits,{packageType:type,maxWeightKg:null,maxLengthCm:null,maxWidthCm:null,maxHeightCm:null,maxCombinedCm:null}]})}
  function updatePackage(type:PackageType,key:keyof Omit<PackageLimit,'packageType'>,value:string){block('limits',{...form.limits,packageLimits:form.limits.packageLimits.map(item=>item.packageType===type?{...item,[key]:numberOrNull(value)}:item)})}
  function toggleDay(kind:'pickupDays'|'deliveryDays',day:Day){const current=form.schedule[kind];block('schedule',{...form.schedule,[kind]:current.includes(day)?current.filter(value=>value!==day):[...current,day]})}
  function toggleSet(kind:'exclusiveCustomerIds'|'blockedAgencies',value:string){const current=form.restrictions[kind];block('restrictions',{...form.restrictions,[kind]:current.includes(value)?current.filter(item=>item!==value):[...current,value]})}
  async function save(event:FormEvent){event.preventDefault();if(!canManage)return;setSaving(true);setError('');try{await json(auth,editing?`${catalogApiUrl}/operational-services/${id}`:`${catalogApiUrl}/operational-services`,{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});navigate('/configuracao/servicos')}catch{setError(saveError)}finally{setSaving(false)}}
  const filteredZones=zones.filter(zone=>`${zone.code} ${zone.designation} ${zone.postalCodePatterns.join(' ')}`.toLowerCase().includes(zoneQuery.toLowerCase()))
  const filteredCustomers=customers.filter(customer=>`${customer.customerCode} ${customer.shippingName}`.toLowerCase().includes(customerQuery.toLowerCase()))
  const serviceOptions=services.filter(value=>value.id!==id)
  return <main className="workspace-page operational-page service-editor-page"><ContextualPageHeading title={editing?'Editar serviço':'Adicionar serviço'} trail={['Configuração comercial','Serviços']}/>
    {error&&<p className="error">{error}</p>}<form className="panel service-form" onSubmit={save}>
      <section><h2>Identificação e classificação</h2><div className="service-grid identity-grid"><label>Código *<input required disabled={!canManage} maxLength={40} value={form.identity.code} onChange={e=>block('identity',{...form.identity,code:e.target.value.toUpperCase()})}/></label><label className="span-2">Designação *<input required disabled={!canManage} value={form.identity.designation} onChange={e=>block('identity',{...form.identity,designation:e.target.value})}/></label><label>Grupo de serviços * <a href="/configuracao/grupos-servicos" onClick={e=>{e.preventDefault();navigate('/configuracao/grupos-servicos')}}>Gerir</a><select required disabled={!canManage} value={form.identity.groupId} onChange={e=>block('identity',{...form.identity,groupId:e.target.value})}><option value="">Selecionar…</option>{groups.map(group=><option key={group.id} value={group.id}>{group.designation}</option>)}</select></label><label>Tipo de transporte<select disabled={!canManage} value={form.identity.transportType} onChange={e=>block('identity',{...form.identity,transportType:e.target.value as ServiceRequest['identity']['transportType']})}><option value="SMALL_VOLUMES">Pequenos volumes</option><option value="LARGE_VOLUMES">Grandes volumes</option></select></label><label className="check-field"><input type="checkbox" disabled={!canManage} checked={form.identity.active} onChange={e=>block('identity',{...form.identity,active:e.target.checked})}/> Serviço ativo</label></div></section>
      <div className="service-columns"><div>
        <section><h2>Zonas e tempos de trânsito <a href="/billing/zones" onClick={e=>{e.preventDefault();navigate('/billing/zones')}}>Gerir zonas</a></h2><div className="service-grid"><label>Tempo mínimo (h)<input disabled={!canManage} type="number" min="0" value={form.transit.transitMinHours??''} onChange={e=>block('transit',{...form.transit,transitMinHours:numberOrNull(e.target.value)})}/></label><label>Tempo máximo (h)<input disabled={!canManage} type="number" min="0" value={form.transit.transitMaxHours??''} onChange={e=>block('transit',{...form.transit,transitMaxHours:numberOrNull(e.target.value)})}/></label><label>Hora-limite<input disabled={!canManage} type="time" value={form.transit.deliveryCutoff??''} onChange={e=>block('transit',{...form.transit,deliveryCutoff:e.target.value||null})}/></label><label>Urgência (1–5)<input disabled={!canManage} type="number" min="1" max="5" value={form.transit.urgency} onChange={e=>block('transit',{...form.transit,urgency:Number(e.target.value)})}/></label></div>
          <div className="zone-selector"><div className="selector-tools"><input value={zoneQuery} onChange={e=>setZoneQuery(e.target.value)} placeholder="Pesquisar zona ou código postal"/><button type="button" className="secondary" disabled={!canManage} onClick={()=>block('transit',{...form.transit,zones:filteredZones.map(zone=>({billingZoneId:zone.id,transitMinHours:null,transitMaxHours:null}))})}>Selecionar visíveis</button><button type="button" className="secondary" disabled={!canManage} onClick={()=>block('transit',{...form.transit,zones:[]})}>Remover todas</button></div>{filteredZones.map(zone=>{const rule=form.transit.zones.find(value=>value.billingZoneId===zone.id);return <div className="zone-rule" key={zone.id}><label><input type="checkbox" disabled={!canManage} checked={Boolean(rule)} onChange={()=>toggleZone(zone)}/><span><strong>{zone.code}</strong> {zone.designation}<small>{zone.postalCodePatterns.join(', ')}</small></span></label>{rule&&<><input aria-label="Trânsito mínimo da zona" disabled={!canManage} type="number" min="0" placeholder="Mín. h" value={rule.transitMinHours??''} onChange={e=>block('transit',{...form.transit,zones:form.transit.zones.map(value=>value.billingZoneId===zone.id?{...value,transitMinHours:numberOrNull(e.target.value)}:value)})}/><input aria-label="Trânsito máximo da zona" disabled={!canManage} type="number" min="0" placeholder="Máx. h" value={rule.transitMaxHours??''} onChange={e=>block('transit',{...form.transit,zones:form.transit.zones.map(value=>value.billingZoneId===zone.id?{...value,transitMaxHours:numberOrNull(e.target.value)}:value)})}/></>}</div>})}</div>
        </section>
        <section><h2>Limites de peso e volumes</h2><div className="package-table">{packages.map(item=>{const limit=packageLimit(item.id);return <div className="package-row" key={item.id}><label><input type="checkbox" disabled={!canManage} checked={Boolean(limit)} onChange={()=>togglePackage(item.id)}/>{item.label}</label>{(['maxWeightKg','maxLengthCm','maxWidthCm','maxHeightCm','maxCombinedCm'] as const).map((field,index)=><input key={field} disabled={!canManage||!limit} type="number" min="0.001" step="0.001" placeholder={['Peso kg','C cm','L cm','A cm','C+L+A'][index]} value={limit?.[field]??''} onChange={e=>updatePackage(item.id,field,e.target.value)}/>)}</div>})}</div><div className="service-grid"><label>Volumes mín.<input disabled={!canManage} type="number" min="0" value={form.limits.totalVolumesMin??''} onChange={e=>block('limits',{...form.limits,totalVolumesMin:numberOrNull(e.target.value)})}/></label><label>Volumes máx.<input disabled={!canManage} type="number" min="0" value={form.limits.totalVolumesMax??''} onChange={e=>block('limits',{...form.limits,totalVolumesMax:numberOrNull(e.target.value)})}/></label><label>Peso total mín. (kg)<input disabled={!canManage} type="number" min="0" step="0.001" value={form.limits.totalWeightMinKg??''} onChange={e=>block('limits',{...form.limits,totalWeightMinKg:numberOrNull(e.target.value)})}/></label><label>Peso total máx. (kg)<input disabled={!canManage} type="number" min="0" step="0.001" value={form.limits.totalWeightMaxKg??''} onChange={e=>block('limits',{...form.limits,totalWeightMaxKg:numberOrNull(e.target.value)})}/></label></div></section>
        <section><h2>Limites de horários</h2><div className="service-grid"><label>Recolha desde<input disabled={!canManage||form.definitions.noPickup} type="time" value={form.schedule.pickupStart??''} onChange={e=>block('schedule',{...form.schedule,pickupStart:e.target.value||null})}/></label><label>Recolha até<input disabled={!canManage||form.definitions.noPickup} type="time" value={form.schedule.pickupEnd??''} onChange={e=>block('schedule',{...form.schedule,pickupEnd:e.target.value||null})}/></label><label>Antecedência (min.)<input disabled={!canManage||form.definitions.noPickup} type="number" min="0" value={form.schedule.minimumAdvanceMinutes??''} onChange={e=>block('schedule',{...form.schedule,minimumAdvanceMinutes:numberOrNull(e.target.value)})}/></label></div><DaySelector label="Dias de recolha" selected={form.schedule.pickupDays} disabled={!canManage||form.definitions.noPickup} toggle={day=>toggleDay('pickupDays',day)}/><DaySelector label="Dias de entrega" selected={form.schedule.deliveryDays} disabled={!canManage} toggle={day=>toggleDay('deliveryDays',day)}/></section>
        <section><h2>Serviço de recolha</h2><div className="service-grid"><label>Serviço associado<select disabled={!canManage||form.definitions.noPickup} value={form.pickupRules.associatedPickupServiceId??''} onChange={e=>block('pickupRules',{...form.pickupRules,associatedPickupServiceId:e.target.value||null})}><option value="">Nenhum</option>{serviceOptions.map(value=><option key={value.id} value={value.id}>{value.code} — {value.designation}</option>)}</select></label><label>Intermunicipal/interurbano<select disabled={!canManage||form.definitions.noPickup} value={form.pickupRules.intercityPickupServiceId??''} onChange={e=>block('pickupRules',{...form.pickupRules,intercityPickupServiceId:e.target.value||null})}><option value="">Nenhum</option>{serviceOptions.map(value=><option key={value.id} value={value.id}>{value.code} — {value.designation}</option>)}</select></label></div></section>
      </div><div>
        <section><h2>Regras de cálculo e venda</h2><div className="service-grid"><label>Regra de preços<select disabled={!canManage} value={form.pricing.priceCalculationRule}><option value="WEIGHT">Por peso</option></select></label><label>Regra da venda<select disabled={!canManage} value={form.pricing.salesCalculationRule}><option value="DEFAULT">Por defeito</option></select></label><label>Forçar transportadora<select disabled={!canManage} value={form.pricing.forcedCarrier??''} onChange={e=>block('pricing',{...form.pricing,forcedCarrier:e.target.value||null})}><option value="">Nenhuma</option>{['LTFT','CTT','DHL','DPD','UPS'].map(value=><option key={value}>{value}</option>)}</select></label><label>IVA<select disabled={!canManage} value={form.pricing.vatMode} onChange={e=>block('pricing',{...form.pricing,vatMode:e.target.value as ServiceRequest['pricing']['vatMode']})}><option value="AUTO">Automático</option><option value="STANDARD">Taxa normal</option><option value="ZERO">0%</option><option value="EXEMPT">Isento</option></select></label></div><CheckGrid disabled={!canManage} value={form.pricing} onChange={value=>block('pricing',value)} fields={[['pricePerVolume','Preço por volume'],['pricePerCubicMeter','Preço por m³'],['pricePerDimensions','Preço por dimensões'],['priceByBracket','Preço por escalão']]}/><p className="field-help">Estas instruções destinam-se ao futuro motor de cálculo e não ligam o serviço às rotas de preços.</p></section>
        <section><h2>Características do transporte</h2><CheckGrid disabled={!canManage} value={form.characteristics} onChange={value=>block('characteristics',value)} fields={[['pickupOnly','Apenas pedido de recolha'],['mailVatZero','Correio (IVA 0%)'],['international','Internacional'],['seaTransport','Via marítima'],['airTransport','Via aérea'],['courier','Estafete'],['forceImport','Forçar importação'],['forceExport','Forçar exportação']]}/></section>
        <section><h2>Serviços adicionais permitidos</h2><CheckGrid disabled={!canManage} value={form.additionalServices} onChange={value=>block('additionalServices',value)} fields={[['allowsCod','Permite reembolso'],['allowsReturn','Permite retorno'],['allowsPudo','Pontos Pickup / PUDO'],['requiresDeliveryPin','PIN de entrega']]}/></section>
        <section><h2>Definições operacionais</h2><CheckGrid disabled={!canManage} value={form.definitions} onChange={value=>{const next=value as ServiceRequest['definitions'];block('definitions',next);if(next.noPickup){block('schedule',{...form.schedule,pickupStart:null,pickupEnd:null,minimumAdvanceMinutes:null,pickupDays:[]});block('pickupRules',{associatedPickupServiceId:null,intercityPickupServiceId:null});block('characteristics',{...form.characteristics,pickupOnly:false})}}} fields={[['requiresEmail','E-mail obrigatório'],['autoSubmitWebservice','Submissão automática'],['requiresKilometres','Quilómetros obrigatórios'],['forceReturn','Forçar retorno'],['noPickup','Sem recolha'],['requiresDimensions','Dimensões obrigatórias'],['insuredValue','Valor seguro']]}/><label>Identificador de mapa<input disabled={!canManage} maxLength={120} value={form.definitions.mapIdentifier??''} onChange={e=>block('definitions',{...form.definitions,mapIdentifier:e.target.value||null})}/></label></section>
        <section><h2>Limitação por cliente ou agência</h2><label>Pesquisar cliente<input value={customerQuery} onChange={e=>setCustomerQuery(e.target.value)} placeholder="Código ou designação"/></label><div className="customer-selector">{filteredCustomers.map(customer=><label key={customer.id}><input type="checkbox" disabled={!canManage} checked={form.restrictions.exclusiveCustomerIds.includes(customer.id)} onChange={()=>toggleSet('exclusiveCustomerIds',customer.id)}/><span><strong>{customer.customerCode}</strong> {customer.shippingName}</span></label>)}</div><p className="field-help">Sem clientes selecionados, o serviço fica disponível para todos.</p><div className="checkbox-grid agencies"><label><input type="checkbox" disabled={!canManage} checked={form.restrictions.blockedAgencies.includes('LTFT01')} onChange={()=>toggleSet('blockedAgencies','LTFT01')}/>Indisponível em [LTFT01] Fafe</label><label><input type="checkbox" disabled={!canManage} checked={form.restrictions.blockedAgencies.includes('LTFT02')} onChange={()=>toggleSet('blockedAgencies','LTFT02')}/>Indisponível em [LTFT02] Taipas</label></div></section>
      </div></div>
      <div className="actions service-actions"><button type="button" className="secondary" onClick={()=>navigate('/configuracao/servicos')}>Fechar</button>{canManage&&<button type="submit" disabled={saving}>{saving?'A guardar…':'Guardar serviço'}</button>}</div>
    </form></main>
}

function DaySelector({label,selected,toggle,disabled}:{label:string;selected:Day[];toggle:(day:Day)=>void;disabled:boolean}){return <div className="day-selector"><strong>{label}</strong>{days.map(day=><label key={day.id}><input type="checkbox" disabled={disabled} checked={selected.includes(day.id)} onChange={()=>toggle(day.id)}/>{day.label}</label>)}</div>}
function CheckGrid<T extends object>({value,onChange,fields,disabled}:{value:T;onChange:(value:T)=>void;fields:[keyof T,string][];disabled:boolean}){return <div className="checkbox-grid">{fields.map(([key,label])=><label key={String(key)}><input type="checkbox" disabled={disabled} checked={Boolean(value[key])} onChange={e=>onChange({...value,[key]:e.target.checked})}/>{label}</label>)}</div>}

export function ServiceGroupsPage({auth}:{auth:AuthSession}){
  const [items,setItems]=useState<Group[]>([]),[id,setId]=useState(''),[designation,setDesignation]=useState(''),[editing,setEditing]=useState<string|null>(null),[error,setError]=useState('')
  const canManage=auth.roles.includes('ADMIN')
  async function load(){try{setItems(await json<Group[]>(auth,`${catalogApiUrl}/service-groups`));setError('')}catch{setError(loadError)}} useEffect(()=>{void load()},[])
  async function save(event:FormEvent){event.preventDefault();try{await json(auth,editing?`${catalogApiUrl}/service-groups/${editing}`:`${catalogApiUrl}/service-groups`,{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(editing?{designation}:{id,designation})});setId('');setDesignation('');setEditing(null);await load()}catch{setError(saveError)}}
  async function toggle(item:Group){try{await json(auth,`${catalogApiUrl}/service-groups/${item.id}/status`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({active:!item.active})});await load()}catch{setError(saveError)}}
  return <main className="workspace-page operational-page"><ContextualPageHeading title="Grupos de serviços" trail={['Configuração comercial','Serviços']}/><section className="panel reference-layout">{canManage&&<form onSubmit={save}><h2>{editing?'Editar grupo':'Novo grupo'}</h2><label>ID *<input required maxLength={40} disabled={Boolean(editing)} value={id} onChange={e=>setId(e.target.value.toUpperCase())}/></label><label>Designação *<input required maxLength={160} value={designation} onChange={e=>setDesignation(e.target.value)}/></label><div className="actions"><button type="button" className="secondary" onClick={()=>{setEditing(null);setId('');setDesignation('')}}>Limpar</button><button type="submit">Guardar</button></div></form>}<div>{error&&<p className="error">{error}</p>}<table><thead><tr><th>ID</th><th>Designação</th><th>Estado</th>{canManage&&<th>Ações</th>}</tr></thead><tbody>{items.map(item=><tr key={item.id}><td>{item.id}</td><td>{item.designation}<small>{item.updatedBy}</small></td><td><span className={`badge ${item.active?'active':''}`}>{item.active?'Ativo':'Inativo'}</span></td>{canManage&&<td><div className="row-actions"><button className="secondary" onClick={()=>{setEditing(item.id);setId(item.id);setDesignation(item.designation)}}>Editar</button><button className="danger-link" onClick={()=>void toggle(item)}>{item.active?'Inativar':'Ativar'}</button></div></td>}</tr>)}</tbody></table></div></section></main>
}

export function BillingZonesPage({auth}:{auth:AuthSession}){
  const blank={code:'',designation:'',zoneType:'DESTINATION_POSTAL_CODES' as const,country:'PT',groupName:'',postalCodes:''}
  const [items,setItems]=useState<Zone[]>([]),[form,setForm]=useState(blank),[editing,setEditing]=useState<string|null>(null),[query,setQuery]=useState(''),[error,setError]=useState('')
  const canManage=auth.roles.includes('ADMIN')
  async function load(){try{setItems(await json<Zone[]>(auth,`${catalogApiUrl}/billing/zones`));setError('')}catch{setError(loadError)}} useEffect(()=>{void load()},[])
  async function save(event:FormEvent){event.preventDefault();const values={code:form.code,designation:form.designation,zoneType:form.zoneType,country:form.country,groupName:form.groupName||null,postalCodePatterns:form.postalCodes.split(',').map(value=>value.trim()).filter(Boolean)};try{await json(auth,editing?`${catalogApiUrl}/billing/zones/${editing}`:`${catalogApiUrl}/billing/zones`,{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(values)});setEditing(null);setForm(blank);await load()}catch{setError(saveError)}}
  async function toggle(item:Zone){try{await json(auth,`${catalogApiUrl}/billing/zones/${item.id}/status`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({active:!item.active})});await load()}catch{setError(saveError)}}
  const filtered=items.filter(item=>`${item.code} ${item.designation} ${item.postalCodePatterns.join(' ')}`.toLowerCase().includes(query.toLowerCase()))
  return <main className="workspace-page operational-page"><ContextualPageHeading title="Zonas de faturação" trail={['Faturação','Zonas']}/><section className="panel billing-zone-layout">{canManage&&<form onSubmit={save}><h2>{editing?'Editar zona':'Adicionar zona de faturação'}</h2><div className="service-grid"><label>Código *<input required maxLength={40} value={form.code} onChange={e=>setForm({...form,code:e.target.value.toUpperCase()})}/></label><label className="span-2">Designação *<input required maxLength={160} value={form.designation} onChange={e=>setForm({...form,designation:e.target.value})}/></label><label>Tipo<select value={form.zoneType} disabled><option value="DESTINATION_POSTAL_CODES">Códigos postais destino</option></select></label><label>País *<input required maxLength={2} value={form.country} onChange={e=>setForm({...form,country:e.target.value.toUpperCase()})}/></label><label>Grupo<input maxLength={120} value={form.groupName} onChange={e=>setForm({...form,groupName:e.target.value})}/></label><label className="span-all">Códigos postais (separados por vírgula) *<textarea required rows={5} value={form.postalCodes} onChange={e=>setForm({...form,postalCodes:e.target.value})}/></label></div><div className="actions"><button type="button" className="secondary" onClick={()=>{setEditing(null);setForm(blank)}}>Limpar</button><button type="submit">Guardar</button></div></form>}<div><div className="catalog-toolbar"><label>Pesquisar<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Zona ou código postal"/></label><span>{filtered.length} zonas</span></div>{error&&<p className="error">{error}</p>}<div className="table-wrap"><table><thead><tr><th>Código</th><th>Designação</th><th>País</th><th>Códigos postais</th><th>Estado</th>{canManage&&<th>Ações</th>}</tr></thead><tbody>{filtered.map(item=><tr key={item.id}><td><strong>{item.code}</strong></td><td>{item.designation}<small>{item.groupName||'Sem grupo'}</small></td><td>{item.country}</td><td>{item.postalCodePatterns.join(', ')}</td><td><span className={`badge ${item.active?'active':''}`}>{item.active?'Ativa':'Inativa'}</span></td>{canManage&&<td><div className="row-actions"><button className="secondary" onClick={()=>{setEditing(item.id);setForm({code:item.code,designation:item.designation,zoneType:item.zoneType,country:item.country,groupName:item.groupName??'',postalCodes:item.postalCodePatterns.join(', ')})}}>Editar</button><button className="danger-link" onClick={()=>void toggle(item)}>{item.active?'Inativar':'Ativar'}</button></div></td>}</tr>)}</tbody></table></div></div></section></main>
}
